name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.17.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile

      - name: Lint
        run: corepack pnpm lint

      - name: Build
        run: corepack pnpm build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        if: github.ref != 'refs/heads/main'
        with:
          name: blog-dist
          path: apps/blog/dist
